# Generated by Django 5.2.14 on 2026-05-12 17:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo_unidade', models.CharField(choices=[('REITORIA', 'Reitoria'), ('CCSH', 'CCSH'), ('CAL', 'CAL'), ('CTISM', 'CTISM')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subunidades', to='unidades.unidade')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['sigla'],
            },
        ),
    ]
