# Generated by Django 5.2.14 on 2026-05-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='tipo_unidade',
            field=models.CharField(choices=[('REITORIA', 'Reitoria'), ('DIRETORIA', 'Diretoria'), ('COORDENACAO', 'Coordenação')], max_length=30),
        ),
    ]
