# Generated by Django 5.2.14 on 2026-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_alter_unidade_tipo_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='tipo_unidade',
            field=models.CharField(choices=[('REITORIA', 'Reitoria'), ('DIRETORIA', 'Diretoria'), ('COORDENACAO', 'Coordenacao')], max_length=30),
        ),
    ]
