# Generated by Django 5.2.14 on 2026-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_criar_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='tipo_unidade',
            field=models.CharField(choices=[('REITORIA', 'Reitoria'), ('DIRETORIA', 'Diretoria'), ('COORDENACAO', 'Coordenação')], max_length=30),
        ),
    ]
