# Generated by Django 5.2.14 on 2026-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0004_risco_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risco',
            name='acao',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva'), ('MONITORAMENTO', 'Monitoramento'), ('CONTINGENCIA', 'Contingência')], max_length=30),
        ),
        migrations.AlterField(
            model_name='risco',
            name='eficacia_controles',
            field=models.CharField(choices=[('INEXISTENTE', 'Inexistente'), ('FRACA', 'Fraca'), ('MEDIANA', 'Mediana'), ('SATISFATORIA', 'Satisfatória'), ('FORTE', 'Forte')], max_length=30),
        ),
        migrations.AlterField(
            model_name='risco',
            name='impacto',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muito baixo'), (2, 'Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Muito alto')]),
        ),
        migrations.AlterField(
            model_name='risco',
            name='probabilidade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muito baixo'), (2, 'Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Muito alto')]),
        ),
        migrations.AlterField(
            model_name='risco',
            name='situacao',
            field=models.CharField(choices=[('NAO_INICIADO', 'Não iniciado'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='risco',
            name='tipo_risco',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('OPERACIONAL', 'Operacional'), ('FINANCEIRO', 'Financeiro'), ('CONFORMIDADE', 'Conformidade'), ('IMAGEM', 'Imagem')], max_length=30),
        ),
    ]
