# Generated by Django 5.2.15 on 2026-06-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0006_recalcular_nivel_residual_planilha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risco',
            name='criado_por_nome',
            field=models.CharField(default='Usuário', max_length=150),
        ),
    ]
