# Generated by Django 5.2.14 on 2026-05-12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("unidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "matricula",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("nome", models.CharField(blank=True, default="", max_length=150)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True, unique=True),
                ),
                (
                    "perfil_acesso",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("ESTUDANTE", "Estudante"),
                        ],
                        default="ESTUDANTE",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usuarios",
                        to="unidades.unidade",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
