# Generated by Django 5.2.14 on 2026-06-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_senha_local_definida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuários'},
        ),
    ]
